// Generated by CoffeeScript 1.3.3
(function() {
  var expect, routes;

  expect = require('chai').expect;

  routes = require('../routes/index');

  describe('routes', function() {
    return describe('index', function() {
      return it('should display the player\'s profile', function() {
        var req, res;
        req = null;
        res = {
          render: function(view, vars) {
            expect(view).to.equal('index');
            return expect(vars.title).to.equal('myLaddr Profile');
          }
        };
        return routes.index(req, res);
      });
    });
  });

}).call(this);
