// Generated by CoffeeScript 1.3.3
(function() {
  var profile;

  profile = require('../models/profile');

  module.exports = {
    index: function(req, res) {
      return res.render('profile', {
        title: 'Profile',
        details: {}
      });
    },
    newuser: function(req, res) {
      profile.add(req.params.fullname);
      return res.redirect('/profile');
    }
  };

}).call(this);
