// Generated by CoffeeScript 1.3.3
(function() {
  var user;

  user = require('../models/user');

  module.exports = {
    index: function(req, res) {
      return res.render('profile', {
        title: 'Profile',
        fullname: req.params.fullname
      });
    },
    newuser: function(req, res) {
      user.add(req.params.fullname);
      return res.redirect('/profile');
    }
  };

}).call(this);
