// Generated by CoffeeScript 1.3.3
(function() {
  var Profile, ProfileSchema, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ProfileSchema = new Schema({
    fullname: String,
    isActive: Boolean
  });

  Profile = mongoose.model('ProfileModel', ProfileSchema);

  module.exports = {
    profile: Profile,
    add: function(fullname) {
      var newProfile;
      newProfile = new Profile({
        fullname: fullname,
        isActive: false
      });
      return newProfile.save(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  };

}).call(this);
