// Generated by CoffeeScript 1.3.3
(function() {
  var Schema, User, UserSchema, mongoose, mongooseAuth;

  mongooseAuth = require('mongoose-auth');

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  UserSchema = new Schema({
    fullname: String,
    isActive: Boolean,
    isAdmin: Boolean
  });

  UserSchema.plugin(mongooseAuth, {
    everymodule: {
      everyauth: {
        User: function() {
          return User;
        }
      }
    },
    facebook: {
      everyauth: {
        myHostname: 'http://localhost:3000',
        appId: '',
        appSecret: '',
        redirectPath: '/'
      }
    }
  });

  User = mongoose.model('User', UserSchema);

  module.exports = {
    user: User,
    add: function(fullname) {
      var newUser;
      newUser = new User({
        fullname: fullname,
        isActive: false,
        isAdmin: false
      });
      return newUser.save(function(err) {
        if (err) {
          throw err;
        }
      });
    }
  };

}).call(this);
